# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from namely_python_sdk.paths.events_id_comments.post import CreateEventCommentRaw
from namely_python_sdk.paths.events_event_id_comments.get import GetEventCommentsRaw
from namely_python_sdk.paths.events_event_id_comments_comment_id.delete import RemoveEventCommentRaw


class CommentsApiRaw(
    CreateEventCommentRaw,
    GetEventCommentsRaw,
    RemoveEventCommentRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
