# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from namely_python_sdk.paths.events.get import EventsRaw
from namely_python_sdk.paths.events.post import Events0Raw
from namely_python_sdk.paths.events_id.get import GetEventRaw


class EventsApiRaw(
    EventsRaw,
    Events0Raw,
    GetEventRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
