# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from namely_python_sdk.paths.teams_id.get import Get
from namely_python_sdk.paths.group_types.get import GetAllGroupTypes
from namely_python_sdk.paths.groups_id.get import GetGroupDetails
from namely_python_sdk.paths.group_types_id.get import GetGroupTypeDetails
from namely_python_sdk.paths.group_types_id_groups.get import GetGroupTypeGroups
from namely_python_sdk.paths.groups.get import Groups
from namely_python_sdk.paths.teams.get import Teams
from namely_python_sdk.apis.tags.groups_teams_api_raw import GroupsTeamsApiRaw


class GroupsTeamsApi(
    Get,
    GetAllGroupTypes,
    GetGroupDetails,
    GetGroupTypeDetails,
    GetGroupTypeGroups,
    Groups,
    Teams,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: GroupsTeamsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = GroupsTeamsApiRaw(api_client)
