# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from namely_python_sdk.paths.group_types.get import GetAllGroupTypes
from namely_python_sdk.paths.groups_id.get import GetGroupDetails
from namely_python_sdk.paths.groups.get import Groups
from namely_python_sdk.apis.tags.groups_api_raw import GroupsApiRaw


class GroupsApi(
    GetAllGroupTypes,
    GetGroupDetails,
    Groups,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: GroupsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = GroupsApiRaw(api_client)
