# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from namely_python_sdk.paths.events_id_comments.post import CreateEventCommentRaw
from namely_python_sdk.paths.likes_event_id.post import CreateEventLikeRaw
from namely_python_sdk.paths.events_id.delete import DeleteAnnouncementRaw
from namely_python_sdk.paths.likes_event_comment_comment_id.delete import DeleteEventCommentLikeRaw
from namely_python_sdk.paths.events.get import EventsRaw
from namely_python_sdk.paths.events.post import Events0Raw
from namely_python_sdk.paths.events_id.get import GetEventRaw
from namely_python_sdk.paths.likes_event_comment_comment_id_recent.get import GetEventCommentLikesRaw
from namely_python_sdk.paths.events_event_id_comments.get import GetEventCommentsRaw
from namely_python_sdk.paths.likes_event_event_id_recent.get import GetEventLikesRaw
from namely_python_sdk.paths.likes_event_comment_comment_id.post import LikeEventCommentRaw
from namely_python_sdk.paths.events_event_id_comments_comment_id.delete import RemoveEventCommentRaw
from namely_python_sdk.paths.likes_event_event_id.delete import RemoveEventLikeRaw


class HomeFeedApiRaw(
    CreateEventCommentRaw,
    CreateEventLikeRaw,
    DeleteAnnouncementRaw,
    DeleteEventCommentLikeRaw,
    EventsRaw,
    Events0Raw,
    GetEventRaw,
    GetEventCommentLikesRaw,
    GetEventCommentsRaw,
    GetEventLikesRaw,
    LikeEventCommentRaw,
    RemoveEventCommentRaw,
    RemoveEventLikeRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
