# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from namely_python_sdk.paths.job_titles.post import CreateJobTitleRaw
from namely_python_sdk.paths.job_titles.get import GetAllJobTitlesRaw
from namely_python_sdk.paths.job_titles_id.get import GetJobTitleByIdRaw
from namely_python_sdk.paths.job_titles_id.put import UpdateJobTitleRaw


class JobTitleApiRaw(
    CreateJobTitleRaw,
    GetAllJobTitlesRaw,
    GetJobTitleByIdRaw,
    UpdateJobTitleRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
