# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from namely_python_sdk.paths.job_tiers.post import CreateJobTierRaw
from namely_python_sdk.paths.job_tiers.get import GetAllJobTiersRaw
from namely_python_sdk.paths.job_tiers_id.get import GetJobTierRaw
from namely_python_sdk.paths.job_tiers_id.put import UpdateLabelRaw


class JobTierApiRaw(
    CreateJobTierRaw,
    GetAllJobTiersRaw,
    GetJobTierRaw,
    UpdateLabelRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
