# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from namely_python_sdk.paths.job_tiers.post import CreateJobTier
from namely_python_sdk.paths.job_tiers.get import GetAllJobTiers
from namely_python_sdk.paths.job_tiers_id.get import GetJobTier
from namely_python_sdk.paths.job_tiers_id.put import UpdateLabel
from namely_python_sdk.apis.tags.job_tier_api_raw import JobTierApiRaw


class JobTierApi(
    CreateJobTier,
    GetAllJobTiers,
    GetJobTier,
    UpdateLabel,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: JobTierApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = JobTierApiRaw(api_client)
