# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from namely_python_sdk.paths.likes_event_event_id_recent.get import GetEventLikes
from namely_python_sdk.apis.tags.likes_api_raw import LikesApiRaw


class LikesApi(
    GetEventLikes,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: LikesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = LikesApiRaw(api_client)
