# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from namely_python_sdk.paths.countries.get import Countries
from namely_python_sdk.paths.countries_id.get import GetCountryDetails
from namely_python_sdk.apis.tags.namely_system_info_api_raw import NamelySystemInfoApiRaw


class NamelySystemInfoApi(
    Countries,
    GetCountryDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: NamelySystemInfoApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = NamelySystemInfoApiRaw(api_client)
