# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from namely_python_sdk.paths.countries.get import CountriesRaw
from namely_python_sdk.paths.countries_id.get import GetCountryDetailsRaw


class NamelySystemInfoApiRaw(
    CountriesRaw,
    GetCountryDetailsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
