# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from namely_python_sdk.paths.profiles_id_notifications.get import GetProfileNotificationsRaw
from namely_python_sdk.paths.notifications.get import NotificationsRaw


class NotificationsApiRaw(
    GetProfileNotificationsRaw,
    NotificationsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
