# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from namely_python_sdk.paths.reports_id.get import GetReportData
from namely_python_sdk.apis.tags.reports_api_raw import ReportsApiRaw


class ReportsApi(
    GetReportData,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ReportsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ReportsApiRaw(api_client)
