# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from namely_python_sdk import Namely

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        namely = Namely(
        
                        authorization = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(namely)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
