# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAddress(TypedDict):
    pass

class OptionalAddress(TypedDict, total=False):
    address1: str

    address2: str

    city: str

    state_id: str

    zip: str

    state: str

    country: str

    country_id: str

    phone: str

class Address(RequiredAddress, OptionalAddress):
    pass
