# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredColumnItem(TypedDict):
    pass

class OptionalColumnItem(TypedDict, total=False):
    # immutable name of the report column
    name: str

    # data type of the report column
    type: str

    # name/label of the report column
    label: str

class ColumnItem(RequiredColumnItem, OptionalColumnItem):
    pass
