# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.company_info_get_info_response_authentications import CompanyInfoGetInfoResponseAuthentications

class RequiredCompanyInfoGetInfoResponse(TypedDict):
    pass

class OptionalCompanyInfoGetInfoResponse(TypedDict, total=False):
    # Compay name
    name: str

    # Company permalink, the subdomain before namely.com
    permalink: str

    # Background image on the login page.
    background_url: str

    # Logo image on the home page.
    logo_url: str

    authentications: CompanyInfoGetInfoResponseAuthentications

class CompanyInfoGetInfoResponse(RequiredCompanyInfoGetInfoResponse, OptionalCompanyInfoGetInfoResponse):
    pass
