# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.country_links import CountryLinks

class RequiredCountry(TypedDict):
    pass

class OptionalCountry(TypedDict, total=False):
    # unique identifier of the profile; 2-digit ISO code; used when passing home or office #model:yq9tkBR24wuBhzizY
    id: str

    # name of the country
    name: str

    # name of the country's subdivision (e.g. State, Province)
    subdivision_type: str

    links: CountryLinks

class Country(RequiredCountry, OptionalCountry):
    pass
