# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.create_group_type_payload import CreateGroupTypePayload

class RequiredCreateGroupType(TypedDict):
    group_types: typing.List[CreateGroupTypePayload]

class OptionalCreateGroupType(TypedDict, total=False):
    pass

class CreateGroupType(RequiredCreateGroupType, OptionalCreateGroupType):
    pass
