# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCreateSectionPayload(TypedDict):
    # name/label of the profile field section
    title: str

class OptionalCreateSectionPayload(TypedDict, total=False):
    pass

class CreateSectionPayload(RequiredCreateSectionPayload, OptionalCreateSectionPayload):
    pass
