# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCreateJobTitlePayload(TypedDict):
    # name/label of the job title you’re creating
    title: str

    # id of the job tier with which you want to associate the job title
    parent: str

class OptionalCreateJobTitlePayload(TypedDict, total=False):
    pass

class CreateJobTitlePayload(RequiredCreateJobTitlePayload, OptionalCreateJobTitlePayload):
    pass
