# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCreateEventPayload(TypedDict):
    # the content of the announcement; formatted in markdown; to @mention a profile, use format: <code>[full_name](https://developers.namely.com/)</code> where {profile_id} is the <code>id</code> of the profile you want to mention
    content: str

class OptionalCreateEventPayload(TypedDict, total=False):
    # if <code>true</code>, any @mentioned profile will be appreciated
    is_appreciation: bool

    file_id: str

    # if <code>true</code>, will send an email to all active profiles per their company email address; will only be successful is token bearer has the corresponding permissions
    email_all: bool

class CreateEventPayload(RequiredCreateEventPayload, OptionalCreateEventPayload):
    pass
