# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.create_profile_field_payload import CreateProfileFieldPayload

class RequiredCreateProfileField(TypedDict):
    fields: typing.List[CreateProfileFieldPayload]

class OptionalCreateProfileField(TypedDict, total=False):
    pass

class CreateProfileField(RequiredCreateProfileField, OptionalCreateProfileField):
    pass
