# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCreateCommentPayload(TypedDict):
    # the content of the comment; formatted in markdown; to @mention a profile, use format: <code>[full_name](https://developers.namely.com/)</code> where {profile_id} is the <code>id</code> of the profile you want to mention
    content: str

class OptionalCreateCommentPayload(TypedDict, total=False):
    pass

class CreateCommentPayload(RequiredCreateCommentPayload, OptionalCreateCommentPayload):
    pass
