# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.create_section_payload import CreateSectionPayload

class RequiredCreateSection(TypedDict):
    sections: typing.List[CreateSectionPayload]

class OptionalCreateSection(TypedDict, total=False):
    pass

class CreateSection(RequiredCreateSection, OptionalCreateSection):
    pass
