# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.delete_like_payload import DeleteLikePayload

class RequiredDeleteLike(TypedDict):
    message: typing.List[DeleteLikePayload]

class OptionalDeleteLike(TypedDict, total=False):
    pass

class DeleteLike(RequiredDeleteLike, OptionalDeleteLike):
    pass
