# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredEventsMeta(TypedDict):
    pass

class OptionalEventsMeta(TypedDict, total=False):
    # HTTP response
    response: int

    # <code>true</code> if the company has commenting enabled on the home feed; same on the <code>event</code> object
    use_comments: bool

    # <code>true</code> if the token bearer has a role with permission to post announcements on the home feed
    use_updates: bool

    # <code>true</code> if the company has mentioning enabled on the home feed
    use_mentions: bool

    # <code>true</code> if the company has appreciations enabled on the home feed
    use_appreciations: bool

    # <code>true</code> if the company has likes enabled on the home feed
    use_likes: bool

    # number of events returned on the page
    count: int

class EventsMeta(RequiredEventsMeta, OptionalEventsMeta):
    pass
