# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.event_links_comments import EventLinksComments

class RequiredEventLinks(TypedDict):
    pass

class OptionalEventLinks(TypedDict, total=False):
    # profile id of the profile related to the event; profile that created the <code>announcement</code> or profile associated with a <code>birthday</code>, <code>anniversary</code>, or <code>recent_arrival
    profile: str

    comments: EventLinksComments

    # unique identifiers of a file associated with the event (photo, document, etc.); zero to one; null for anything but type: <code>announcement</code>
    file: str

    # <code>id</code> of any profiles \"appreciated\" in the content of the event; all \"mentioned\" profiles in the content of an appreciation announcement will also be listed here; zero to many; null for anything but type: <code>announcement</code>; null if event is not an appreciation
    appreciations: typing.List[str]

class EventLinks(RequiredEventLinks, OptionalEventLinks):
    pass
