# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.field_links import FieldLinks

RequiredField = TypedDict("RequiredField", {
    })

OptionalField = TypedDict("OptionalField", {
    # unique identifier of the profile field
    "id": str,

    # immutable name of the profile field; auto created based on label if using UI to create profile field
    "name": str,

    # label of the profile field; editable on UI and through API
    "label": str,

    # immutable data type of the profile field; valid values include <code>text</code>, <code>image</code>, <code>referencehistory</code> (<code>job_title</code> only), <code>select</code>, <code>date</code>, <code>email</code>, <code>longtext</code>, <code>checkboxes</code>, <code>address</code>, <code>address</code>, <code>file</code>, <code>referenceselect</code> (<code>user_status</code> only), <code>salary</code>, <code>number</code>, <code>address</code>
    "type": str,

    # N/A - no longer supported
    "default": bool,

    # <code>true</code> if the profile field is able to be deleted
    "deletable": bool,

    # valid format information for passing data through the API for the profile field
    "valid_format_info": str,

    # refers to the profile field \"block\" in which the profile field is located (included in \"linked\"); sequentially corresponds based the position of the block title; top position is 0
    "block_index": int,

    "links": FieldLinks,

    # N/A - no longer supported
    "example": bool,

    # N/A - no longer supported
    "x-konfig-original-example": bool,
    }, total=False)

class Field(RequiredField, OptionalField):
    pass
