# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredFieldLinks(TypedDict):
    pass

class OptionalFieldLinks(TypedDict, total=False):
    # unique identifier of the #endpoint:66aqLXinWcyrR2aY2 in which the profile field is located
    section: str

class FieldLinks(RequiredFieldLinks, OptionalFieldLinks):
    pass
