# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.event import Event
from namely_python_sdk.type.events_meta import EventsMeta
from namely_python_sdk.type.get_events_response_linked import GetEventsResponseLinked
from namely_python_sdk.type.get_events_response_links import GetEventsResponseLinks

class RequiredGetEventsResponse(TypedDict):
    pass

class OptionalGetEventsResponse(TypedDict, total=False):
    events: typing.List[Event]

    meta: EventsMeta

    links: GetEventsResponseLinks

    linked: GetEventsResponseLinked

class GetEventsResponse(RequiredGetEventsResponse, OptionalGetEventsResponse):
    pass
