# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.get_groups_response_linked import GetGroupsResponseLinked
from namely_python_sdk.type.get_groups_response_links import GetGroupsResponseLinks
from namely_python_sdk.type.group import Group
from namely_python_sdk.type.meta_group import MetaGroup

class RequiredGetGroupsResponse(TypedDict):
    pass

class OptionalGetGroupsResponse(TypedDict, total=False):
    groups: typing.List[Group]

    meta: MetaGroup

    links: GetGroupsResponseLinks

    linked: GetGroupsResponseLinked

class GetGroupsResponse(RequiredGetGroupsResponse, OptionalGetGroupsResponse):
    pass
