# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.get_resources_response_meta import GetResourcesResponseMeta
from namely_python_sdk.type.resource import Resource

class RequiredGetResourcesResponse(TypedDict):
    pass

class OptionalGetResourcesResponse(TypedDict, total=False):
    resources: typing.List[Resource]

    meta: GetResourcesResponseMeta

class GetResourcesResponse(RequiredGetResourcesResponse, OptionalGetResourcesResponse):
    pass
