# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredGroupType(TypedDict):
    pass

class OptionalGroupType(TypedDict, total=False):
    # name/label of the group type
    title: str

    # unique identifier of the group type
    id: str

    # immutable, system generated field name for the group type
    field_name: str

    # denotes whether or not the group can be deleted by someone with the appropriate permissions; <code>true</code> for all groups except Departments and Office Location.
    deletable: bool

    # returns one of three group types: office location, department, or custom; location and department are system delivered groups (will also not be deletable)
    type: str

    # <code>true</code> if the group type has been chosen to display on the \"Teams\" page in Namely, eligible for @mention (additional permissions apply)
    x_groups_as_teams: bool

class GroupType(RequiredGroupType, OptionalGroupType):
    pass
