# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredGroupLink(TypedDict):
    pass

class OptionalGroupLink(TypedDict, total=False):
    # unique identifier of the group
    id: str

    # name/label of the group
    name: str

class GroupLink(RequiredGroupLink, OptionalGroupLink):
    pass
