# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.link import Link

RequiredHomeFeedGetEventResponseLinks = TypedDict("RequiredHomeFeedGetEventResponseLinks", {
    })

OptionalHomeFeedGetEventResponseLinks = TypedDict("OptionalHomeFeedGetEventResponseLinks", {
    "events.profile": Link,

    "events.comments": Link,

    "events.file": Link,

    "comments.profile": Link,

    "profile.image": Link,
    }, total=False)

class HomeFeedGetEventResponseLinks(RequiredHomeFeedGetEventResponseLinks, OptionalHomeFeedGetEventResponseLinks):
    pass
