# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.event import Event
from namely_python_sdk.type.events_meta import EventsMeta
from namely_python_sdk.type.home_feed_get_event_response_linked import HomeFeedGetEventResponseLinked
from namely_python_sdk.type.home_feed_get_event_response_links import HomeFeedGetEventResponseLinks

class RequiredHomeFeedGetEventResponse(TypedDict):
    pass

class OptionalHomeFeedGetEventResponse(TypedDict, total=False):
    events: typing.List[Event]

    meta: EventsMeta

    links: HomeFeedGetEventResponseLinks

    linked: HomeFeedGetEventResponseLinked

class HomeFeedGetEventResponse(RequiredHomeFeedGetEventResponse, OptionalHomeFeedGetEventResponse):
    pass
