# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.comment import Comment
from namely_python_sdk.type.comment_meta import CommentMeta
from namely_python_sdk.type.home_feed_get_event_comments_response_linked import HomeFeedGetEventCommentsResponseLinked
from namely_python_sdk.type.home_feed_get_event_comments_response_links import HomeFeedGetEventCommentsResponseLinks

class RequiredHomeFeedGetEventCommentsResponse(TypedDict):
    pass

class OptionalHomeFeedGetEventCommentsResponse(TypedDict, total=False):
    events: typing.List[Comment]

    meta: CommentMeta

    links: HomeFeedGetEventCommentsResponseLinks

    linked: HomeFeedGetEventCommentsResponseLinked

class HomeFeedGetEventCommentsResponse(RequiredHomeFeedGetEventCommentsResponse, OptionalHomeFeedGetEventCommentsResponse):
    pass
