# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredHomeFeedRemoveEventLikeResponse(TypedDict):
    pass

class OptionalHomeFeedRemoveEventLikeResponse(TypedDict, total=False):
    message: str

class HomeFeedRemoveEventLikeResponse(RequiredHomeFeedRemoveEventLikeResponse, OptionalHomeFeedRemoveEventLikeResponse):
    pass
