# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.home_feed_create_event_like_response_message import HomeFeedCreateEventLikeResponseMessage

class RequiredHomeFeedCreateEventLikeResponse(TypedDict):
    pass

class OptionalHomeFeedCreateEventLikeResponse(TypedDict, total=False):
    message: HomeFeedCreateEventLikeResponseMessage

class HomeFeedCreateEventLikeResponse(RequiredHomeFeedCreateEventLikeResponse, OptionalHomeFeedCreateEventLikeResponse):
    pass
