# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.file import File
from namely_python_sdk.type.linked_profile import LinkedProfile

class RequiredHomeFeedGetEventCommentsResponseLinked(TypedDict):
    pass

class OptionalHomeFeedGetEventCommentsResponseLinked(TypedDict, total=False):
    profiles: typing.List[LinkedProfile]

    files: typing.List[File]

class HomeFeedGetEventCommentsResponseLinked(RequiredHomeFeedGetEventCommentsResponseLinked, OptionalHomeFeedGetEventCommentsResponseLinked):
    pass
