# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.like import Like

class RequiredHomeFeedGetEventLikesResponse(TypedDict):
    pass

class OptionalHomeFeedGetEventLikesResponse(TypedDict, total=False):
    likes: typing.List[Like]

class HomeFeedGetEventLikesResponse(RequiredHomeFeedGetEventLikesResponse, OptionalHomeFeedGetEventLikesResponse):
    pass
