# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredJobTitleLink(TypedDict):
    pass

class OptionalJobTitleLink(TypedDict, total=False):
    # name/label of the job title
    title: str

    # unique identifier of the job title
    id: str

class JobTitleLink(RequiredJobTitleLink, OptionalJobTitleLink):
    pass
