# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.job_tier import JobTier
from namely_python_sdk.type.jobs_info_get_job_tier_response_linked import JobsInfoGetJobTierResponseLinked
from namely_python_sdk.type.jobs_info_get_job_tier_response_links import JobsInfoGetJobTierResponseLinks
from namely_python_sdk.type.meta import Meta

class RequiredJobsInfoGetJobTierResponse(TypedDict):
    pass

class OptionalJobsInfoGetJobTierResponse(TypedDict, total=False):
    job_tiers: typing.List[JobTier]

    meta: Meta

    links: JobsInfoGetJobTierResponseLinks

    linked: JobsInfoGetJobTierResponseLinked

class JobsInfoGetJobTierResponse(RequiredJobsInfoGetJobTierResponse, OptionalJobsInfoGetJobTierResponse):
    pass
