# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.job_tier import JobTier
from namely_python_sdk.type.jobs_info_update_label_response_linked import JobsInfoUpdateLabelResponseLinked
from namely_python_sdk.type.jobs_info_update_label_response_links import JobsInfoUpdateLabelResponseLinks
from namely_python_sdk.type.meta import Meta

class RequiredJobsInfoUpdateLabelResponse(TypedDict):
    pass

class OptionalJobsInfoUpdateLabelResponse(TypedDict, total=False):
    job_tiers: typing.List[JobTier]

    meta: Meta

    links: JobsInfoUpdateLabelResponseLinks

    linked: JobsInfoUpdateLabelResponseLinked

class JobsInfoUpdateLabelResponse(RequiredJobsInfoUpdateLabelResponse, OptionalJobsInfoUpdateLabelResponse):
    pass
