# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.job_title import JobTitle
from namely_python_sdk.type.jobs_info_create_job_title_response_linked import JobsInfoCreateJobTitleResponseLinked
from namely_python_sdk.type.jobs_info_create_job_title_response_links import JobsInfoCreateJobTitleResponseLinks
from namely_python_sdk.type.meta import Meta

class RequiredJobsInfoCreateJobTitleResponse(TypedDict):
    pass

class OptionalJobsInfoCreateJobTitleResponse(TypedDict, total=False):
    job_titles: typing.List[JobTitle]

    meta: Meta

    links: JobsInfoCreateJobTitleResponseLinks

    linked: JobsInfoCreateJobTitleResponseLinked

class JobsInfoCreateJobTitleResponse(RequiredJobsInfoCreateJobTitleResponse, OptionalJobsInfoCreateJobTitleResponse):
    pass
