# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.job_title import JobTitle
from namely_python_sdk.type.jobs_info_get_job_title_by_id_response_linked import JobsInfoGetJobTitleByIdResponseLinked
from namely_python_sdk.type.jobs_info_get_job_title_by_id_response_links import JobsInfoGetJobTitleByIdResponseLinks
from namely_python_sdk.type.meta import Meta

class RequiredJobsInfoGetJobTitleByIdResponse(TypedDict):
    pass

class OptionalJobsInfoGetJobTitleByIdResponse(TypedDict, total=False):
    job_titles: typing.List[JobTitle]

    meta: Meta

    links: JobsInfoGetJobTitleByIdResponseLinks

    linked: JobsInfoGetJobTitleByIdResponseLinked

class JobsInfoGetJobTitleByIdResponse(RequiredJobsInfoGetJobTitleByIdResponse, OptionalJobsInfoGetJobTitleByIdResponse):
    pass
