# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.job_title import JobTitle
from namely_python_sdk.type.jobs_info_update_job_title_response_linked import JobsInfoUpdateJobTitleResponseLinked
from namely_python_sdk.type.jobs_info_update_job_title_response_links import JobsInfoUpdateJobTitleResponseLinks
from namely_python_sdk.type.meta import Meta

class RequiredJobsInfoUpdateJobTitleResponse(TypedDict):
    pass

class OptionalJobsInfoUpdateJobTitleResponse(TypedDict, total=False):
    job_titles: typing.List[JobTitle]

    meta: Meta

    links: JobsInfoUpdateJobTitleResponseLinks

    linked: JobsInfoUpdateJobTitleResponseLinked

class JobsInfoUpdateJobTitleResponse(RequiredJobsInfoUpdateJobTitleResponse, OptionalJobsInfoUpdateJobTitleResponse):
    pass
