# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.job_title import JobTitle
from namely_python_sdk.type.jobs_info_get_all_job_titles_response_linked import JobsInfoGetAllJobTitlesResponseLinked
from namely_python_sdk.type.jobs_info_get_all_job_titles_response_links import JobsInfoGetAllJobTitlesResponseLinks
from namely_python_sdk.type.meta import Meta

class RequiredJobsInfoGetAllJobTitlesResponse(TypedDict):
    pass

class OptionalJobsInfoGetAllJobTitlesResponse(TypedDict, total=False):
    job_titles: typing.List[JobTitle]

    meta: Meta

    links: JobsInfoGetAllJobTitlesResponseLinks

    linked: JobsInfoGetAllJobTitlesResponseLinked

class JobsInfoGetAllJobTitlesResponse(RequiredJobsInfoGetAllJobTitlesResponse, OptionalJobsInfoGetAllJobTitlesResponse):
    pass
