# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.link import Link

RequiredJobsInfoUpdateJobTitleResponseLinks = TypedDict("RequiredJobsInfoUpdateJobTitleResponseLinks", {
    })

OptionalJobsInfoUpdateJobTitleResponseLinks = TypedDict("OptionalJobsInfoUpdateJobTitleResponseLinks", {
    "job_titles.job_tier": Link,
    }, total=False)

class JobsInfoUpdateJobTitleResponseLinks(RequiredJobsInfoUpdateJobTitleResponseLinks, OptionalJobsInfoUpdateJobTitleResponseLinks):
    pass
