# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.like_links import LikeLinks

class RequiredLike(TypedDict):
    pass

class OptionalLike(TypedDict, total=False):
    # unique identifier of the like
    id: str

    # a link to the profile of \"liker\"
    href: str

    # full name of the \"liker\" per his/her profile
    full_name: str

    # label of the job title of the \"liker\" per his/her profile
    job_title: str

    links: LikeLinks

class Like(RequiredLike, OptionalLike):
    pass
