# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.linked_profile_image import LinkedProfileImage

class RequiredLinkedProfile(TypedDict):
    pass

class OptionalLinkedProfile(TypedDict, total=False):
    id: str

    email: str

    first_name: str

    last_name: str

    user_status: str

    updated_at: int

    created_at: int

    preferred_name: str

    image: LinkedProfileImage

    full_name: str

class LinkedProfile(RequiredLinkedProfile, OptionalLinkedProfile):
    pass
