# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.mention_notification_links_team_ids import MentionNotificationLinksTeamIds

class RequiredMentionNotificationLinks(TypedDict):
    pass

class OptionalMentionNotificationLinks(TypedDict, total=False):
    # id of the profile that created the post or comment
    profile_id: str

    # only present if the notification is in re: a comment; id of the comment you were mentioned in (can't be appreciated in a comment)
    comment_id: str

    # id of the event you were mentioned/appreciated in or the event that the comment you were mentioned in is associated with
    event_id: str

    team_ids: MentionNotificationLinksTeamIds

class MentionNotificationLinks(RequiredMentionNotificationLinks, OptionalMentionNotificationLinks):
    pass
