# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.mention_notification_links import MentionNotificationLinks

class RequiredMentionNotification(TypedDict):
    pass

class OptionalMentionNotification(TypedDict, total=False):
    # unique identifier of the notification
    id: int

    # content of the notification
    text: str

    # always social.mentioned
    type: str

    # epoch time that the event was created/generated
    timestamp: int

    # <code>true</code> if the token bearer has viewed the list of notifications since this notification was created
    seen: str

    # <code>true</code> if the token bearer has clicked/tapped on the the notification
    read: str

    links: MentionNotificationLinks

class MentionNotification(RequiredMentionNotification, OptionalMentionNotification):
    pass
