# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.generic_notification import GenericNotification
from namely_python_sdk.type.notifications_get_profile_notifications_response_linked import NotificationsGetProfileNotificationsResponseLinked
from namely_python_sdk.type.notifications_get_profile_notifications_response_links import NotificationsGetProfileNotificationsResponseLinks

class RequiredNotificationsGetProfileNotificationsResponse(TypedDict):
    pass

class OptionalNotificationsGetProfileNotificationsResponse(TypedDict, total=False):
    notifications: GenericNotification

    links: NotificationsGetProfileNotificationsResponseLinks

    linked: NotificationsGetProfileNotificationsResponseLinked

class NotificationsGetProfileNotificationsResponse(RequiredNotificationsGetProfileNotificationsResponse, OptionalNotificationsGetProfileNotificationsResponse):
    pass
