# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPayGroup(TypedDict):
    pass

class OptionalPayGroup(TypedDict, total=False):
    title: str

    id: str

    pay_period_name: str

    pay_period_per_year: int

    payroll_company_id: str

    read_only: bool

class PayGroup(RequiredPayGroup, OptionalPayGroup):
    pass
