# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPayrollJob(TypedDict):
    pass

class OptionalPayrollJob(TypedDict, total=False):
    id: str

    name: str

    code: str

    is_active: bool

    is_default: bool

    is_active_formatted: str

    payroll_company_id: str

class PayrollJob(RequiredPayrollJob, OptionalPayrollJob):
    pass
