# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPayrollCompany(TypedDict):
    pass

class OptionalPayrollCompany(TypedDict, total=False):
    id: str

    name: str

    ein: str

    external_id: str

class PayrollCompany(RequiredPayrollCompany, OptionalPayrollCompany):
    pass
