# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.event import Event
from namely_python_sdk.type.events_meta import EventsMeta
from namely_python_sdk.type.post_events_response_linked import PostEventsResponseLinked
from namely_python_sdk.type.post_events_response_links import PostEventsResponseLinks

class RequiredPostEventsResponse(TypedDict):
    pass

class OptionalPostEventsResponse(TypedDict, total=False):
    events: typing.List[Event]

    meta: EventsMeta

    links: PostEventsResponseLinks

    linked: PostEventsResponseLinked

class PostEventsResponse(RequiredPostEventsResponse, OptionalPostEventsResponse):
    pass
