# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.comment import Comment
from namely_python_sdk.type.file import File
from namely_python_sdk.type.profile import Profile

class RequiredPostEventsResponseLinked(TypedDict):
    pass

class OptionalPostEventsResponseLinked(TypedDict, total=False):
    profiles: typing.List[Profile]

    comments: typing.List[Comment]

    files: typing.List[File]

class PostEventsResponseLinked(RequiredPostEventsResponseLinked, OptionalPostEventsResponseLinked):
    pass
