# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


RequiredProfileFieldsCreateProfileFieldResponseLinks = TypedDict("RequiredProfileFieldsCreateProfileFieldResponseLinks", {
    })

OptionalProfileFieldsCreateProfileFieldResponseLinks = TypedDict("OptionalProfileFieldsCreateProfileFieldResponseLinks", {
    "fields.sections": str,
    }, total=False)

class ProfileFieldsCreateProfileFieldResponseLinks(RequiredProfileFieldsCreateProfileFieldResponseLinks, OptionalProfileFieldsCreateProfileFieldResponseLinks):
    pass
