# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.profile import Profile
from namely_python_sdk.type.profiles_update_profile_with_new_job_title_response_linked import ProfilesUpdateProfileWithNewJobTitleResponseLinked
from namely_python_sdk.type.profiles_update_profile_with_new_job_title_response_links import ProfilesUpdateProfileWithNewJobTitleResponseLinks
from namely_python_sdk.type.profiles_update_profile_with_new_job_title_response_meta import ProfilesUpdateProfileWithNewJobTitleResponseMeta

class RequiredProfilesUpdateProfileWithNewJobTitleResponse(TypedDict):
    pass

class OptionalProfilesUpdateProfileWithNewJobTitleResponse(TypedDict, total=False):
    profiles: typing.List[Profile]

    meta: ProfilesUpdateProfileWithNewJobTitleResponseMeta

    links: ProfilesUpdateProfileWithNewJobTitleResponseLinks

    linked: ProfilesUpdateProfileWithNewJobTitleResponseLinked

class ProfilesUpdateProfileWithNewJobTitleResponse(RequiredProfilesUpdateProfileWithNewJobTitleResponse, OptionalProfilesUpdateProfileWithNewJobTitleResponse):
    pass
