# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.dental import Dental
from namely_python_sdk.type.healthcare import Healthcare
from namely_python_sdk.type.home import Home
from namely_python_sdk.type.image import Image
from namely_python_sdk.type.job_title_link import JobTitleLink
from namely_python_sdk.type.office import Office
from namely_python_sdk.type.profile_employee_type import ProfileEmployeeType
from namely_python_sdk.type.profile_links import ProfileLinks
from namely_python_sdk.type.profile_reports_to import ProfileReportsTo
from namely_python_sdk.type.salary import Salary

class RequiredProfile(TypedDict):
    pass

class OptionalProfile(TypedDict, total=False):
    # unique identifier of the profile
    id: str

    # company email of the profile
    email: str

    # first name of the profile
    first_name: str

    # last name of the profile
    last_name: str

    # user status of the profile; valid values in the API are <code>active</code>, <code>pending</code>, and <code>inactive</code>
    user_status: str

    # epoch time that the profile was updated; equal to <code>create_at</code> if never updated
    updated_at: int

    # epoch time that the profile was created
    created_at: int

    # preferred name of the profile; <code>null</code> if never provided; blank if provided then deleted
    preferred_name: str

    image: Image

    # combination of <code>first_name</code> and <code>last_name</code>
    full_name: str

    job_title: JobTitleLink

    reports_to: ProfileReportsTo

    employee_type: ProfileEmployeeType

    # returns the type of access_role assigned to the profile
    access_role: str

    # self described ethnicity of the profile; <code>null</code> if never provided
    ethnicity: typing.Optional[str]

    links: ProfileLinks

    # middle name of the profile; <code>null</code> if never provided; blank if provided then deleted
    middle_name: str

    # gender of the profile; <code>null</code> if never provided; valid values include <code>Male</code> and <code>Female</code>
    gender: str

    # job change reason of the profile; <code>null</code> if never provided; valid values include <code>New Hire</code>, <code>Salary Change</code>, <code>Promotion</code>, and <code>Transfer</code>
    job_change_reason: str

    # terminated reason of the profile; <code>null</code> if never provided
    terminated_reason: str

    # start date of the profile; format <code>YYYY-MM-DD</code>
    start_date: str

    # departure date of the profile; format <code>YYYY-MM-DD</code>; blank if never provided or provided then deleted
    departure_date: str

    # employee id of the profile; blank if never provided or provided then deleted
    employee_id: str

    # employee id of the profile; blank if never provided or provided then deleted
    personal_email: str

    # date of birth of the profile; format <code>YYYY-MM-DD</code>; blank if never provided or provided then deleted
    dob: str

    # ssn of the profile; blank if never provided or provided then deleted
    ssn: str

    # marital status of the profile; <code>null</code> if never provided; valid values include <code>Single</code>, <code>Married</code>, <code>Civil Partnership</code>, <code>Separated</code>, and <code>Divorced</code>
    marital_status: str

    # bio of the profile; <code>null</code> if never provided; blank if provided then deleted
    bio: str

    # list of assets on the profile; blank if never provided or provided then deleted; valid values include <code>Laptop</code>, <code>Cell Phone</code>, <code>Building Keys</code>, <code>Corporate Card</code>, and <code>Air Card</code>
    asset_management: str

    # laptop asset number of the profile; <code>null</code> if never provided; blank if provided then deleted
    laptop_asset_number: str

    # corporate card number of the profile; <code>null</code> if never provided; blank if provided then deleted
    corporate_card_member: str

    # key tag number of the profile; <code>null</code> if never provided; blank if provided then deleted
    key_tag_number: str

    # linkedin_url of the profile; <code>null</code> if never provided; blank if provided then deleted
    linkedin_url: str

    # office main number of the profile; <code>null</code> if never provided; blank if provided then deleted
    office_main_number: str

    # office direct dial number of the profile; <code>null</code> if never provided; blank if provided then deleted
    office_direct_dial: str

    # office phone number of the profile; <code>null</code> if never provided; blank if provided then deleted
    office_phone: str

    # office fax number of the profile; <code>null</code> if never provided; blank if provided then deleted
    office_fax: str

    # office company mobile phone number of the profile; <code>null</code> if never provided; blank if provided then deleted
    office_company_mobile: str

    # home phone number of the profile; <code>null</code> if never provided; blank if provided then deleted
    home_phone: str

    # mobile phone number of the profile; <code>null</code> if never provided; blank if provided then deleted
    mobile_phone: str

    home: Home

    office: Office

    # name of the profile's emergency contact; <code>null</code> if never provided; blank if provided then deleted
    emergency_contact: str

    # phone number of the profile's emergency contact; <code>null</code> if never provided; blank if provided then deleted
    emergency_contact_phone: str

    # resume of the profile; <code>null</code> if never provided; blank if provided then deleted
    resume: str

    # current job description of of the profile; <code>null</code> if never provided; blank if provided then deleted
    current_job_description: str

    # current job description of of the profile; <code>null</code> if never provided; blank if provided then deleted
    job_description: str

    salary: Salary

    healthcare: Healthcare

    # description of the profile's healthcare plan; <code>null</code> if never provided; blank if provided then deleted
    healthcare_info: str

    dental: Dental

    # description of the profile's dental plan; <code>null</code> if never provided; blank if provided then deleted
    dental_info: str

    # description of the profile's vision plan; <code>null</code> if never provided; blank if provided then deleted
    vision_plan_info: str

    # description of the profile's life insurance plan; <code>null</code> if never provided; blank if provided then deleted
    life_insurance_info: str

    # only applies to companies using Namely Time
    namely_time_employee_role: str

    # only applies to companies using Namely Time
    namely_time_manager_role: str

class Profile(RequiredProfile, OptionalProfile):
    pass
