# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.from_namely_python_sdk_model_group_link_import_group_link import FromNamelyPythonSdkModelGroupLinkImportGroupLink
from namely_python_sdk.type.from_namely_python_sdk_model_job_title_link_import_job_title_link import FromNamelyPythonSdkModelJobTitleLinkImportJobTitleLink
from namely_python_sdk.type.from_namely_python_sdk_model_team_link_import_team_link import FromNamelyPythonSdkModelTeamLinkImportTeamLink
from namely_python_sdk.type.group_link import GroupLink
from namely_python_sdk.type.job_title_link import JobTitleLink
from namely_python_sdk.type.team_link import TeamLink

RequiredProfileLinks = TypedDict("RequiredProfileLinks", {
    })

OptionalProfileLinks = TypedDict("OptionalProfileLinks", {
    "job_title": JobTitleLink,

    "groups": typing.List[GroupLink],

    "teams": typing.List[TeamLink],

    "": str,
    }, total=False)

class ProfileLinks(RequiredProfileLinks, OptionalProfileLinks):
    pass
