# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.profile import Profile
from namely_python_sdk.type.profile_links import ProfileLinks
from namely_python_sdk.type.profile_meta import ProfileMeta
from namely_python_sdk.type.profiles_get_profile_by_id_response_linked import ProfilesGetProfileByIdResponseLinked

class RequiredProfilesGetProfileByIdResponse(TypedDict):
    pass

class OptionalProfilesGetProfileByIdResponse(TypedDict, total=False):
    profiles: typing.List[Profile]

    meta: ProfileMeta

    links: ProfileLinks

    linked: ProfilesGetProfileByIdResponseLinked

class ProfilesGetProfileByIdResponse(RequiredProfilesGetProfileByIdResponse, OptionalProfilesGetProfileByIdResponse):
    pass
