# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.column import Column
from namely_python_sdk.type.content import Content

class RequiredReport(TypedDict):
    pass

class OptionalReport(TypedDict, total=False):
    # unique identifier of the report; identical to the <code>id</code> in the path parameters
    id: str

    # describes the type of report (e.g. salary_history)
    type: str

    columns: typing.List[Column]

    content: typing.List[Content]

    links: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

class Report(RequiredReport, OptionalReport):
    pass
