# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTeamLink(TypedDict):
    pass

class OptionalTeamLink(TypedDict, total=False):
    # unique identifier of the team
    id: str

    # name/label of the team
    name: str

class TeamLink(RequiredTeamLink, OptionalTeamLink):
    pass
