# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.team_links_team_categories import TeamLinksTeamCategories

class RequiredTeamLinks(TypedDict):
    pass

class OptionalTeamLinks(TypedDict, total=False):
    team_categories: TeamLinksTeamCategories

class TeamLinks(RequiredTeamLinks, OptionalTeamLinks):
    pass
