# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.update_folder_payload import UpdateFolderPayload

class RequiredUpdateFolder(TypedDict):
    folders: typing.List[UpdateFolderPayload]

class OptionalUpdateFolder(TypedDict, total=False):
    pass

class UpdateFolder(RequiredUpdateFolder, OptionalUpdateFolder):
    pass
