# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.update_group_type_payload import UpdateGroupTypePayload

class RequiredUpdateGroupType(TypedDict):
    group_types: typing.List[UpdateGroupTypePayload]

class OptionalUpdateGroupType(TypedDict, total=False):
    pass

class UpdateGroupType(RequiredUpdateGroupType, OptionalUpdateGroupType):
    pass
