# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredUpdateProfileFieldPayload(TypedDict):
    pass

class OptionalUpdateProfileFieldPayload(TypedDict, total=False):
    # [new] label of the profile field; cannot contain special characters; cannot contain word \"id\"; must be unique; immutable <code>name</code> will be auto-generated based on label
    label: str

    # id of the [new] profile field section in which you want the place the field
    section: str

class UpdateProfileFieldPayload(RequiredUpdateProfileFieldPayload, OptionalUpdateProfileFieldPayload):
    pass
