# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredUpdateProfilePayload(TypedDict):
    pass

class OptionalUpdateProfilePayload(TypedDict, total=False):
    # company email of the profile
    email: str

    first_name: str

    last_name: str

    # valid values are <code>active</code> or <code>pending</code>
    user_status: str

    # valid format is YYYY-MM-DD
    start_date: str

    # REQUIRED if <code>user_status</code> = <code>pending</code>
    personal_email: str

    # <code>id</code>of the profile you'd like to assign as the manager of the profile you're creating
    reports_to: str

    # in addition to passing the <code>id</code> of the <code>job title</code>, you can also pass the <code>title</code>, however, it is case-sensitive
    job_title: str

class UpdateProfilePayload(RequiredUpdateProfilePayload, OptionalUpdateProfilePayload):
    pass
