# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from namely_python_sdk.type.update_group_payload import UpdateGroupPayload

class RequiredUpdateGroup(TypedDict):
    groups: typing.List[UpdateGroupPayload]

class OptionalUpdateGroup(TypedDict, total=False):
    pass

class UpdateGroup(RequiredUpdateGroup, OptionalUpdateGroup):
    pass
