# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.profile_fields_create_profile_field_response import ProfileFieldsCreateProfileFieldResponse
from namely_python_sdk import configuration


class TestProfileFieldsCreateProfileFieldResponse(unittest.TestCase):
    """ProfileFieldsCreateProfileFieldResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
