# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.jobs_info_get_job_tier_response_links import JobsInfoGetJobTierResponseLinks
from namely_python_sdk import configuration


class TestJobsInfoGetJobTierResponseLinks(unittest.TestCase):
    """JobsInfoGetJobTierResponseLinks unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
