# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.get_teams_response_linked import GetTeamsResponseLinked
from namely_python_sdk import configuration


class TestGetTeamsResponseLinked(unittest.TestCase):
    """GetTeamsResponseLinked unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
