# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.home_feed_delete_announcement_response import HomeFeedDeleteAnnouncementResponse
from namely_python_sdk import configuration


class TestHomeFeedDeleteAnnouncementResponse(unittest.TestCase):
    """HomeFeedDeleteAnnouncementResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
