# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.update_group_payload import UpdateGroupPayload
from namely_python_sdk import configuration


class TestUpdateGroupPayload(unittest.TestCase):
    """UpdateGroupPayload unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
