# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.home_feed_create_event_like_response import HomeFeedCreateEventLikeResponse
from namely_python_sdk import configuration


class TestHomeFeedCreateEventLikeResponse(unittest.TestCase):
    """HomeFeedCreateEventLikeResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
