# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.create_event import CreateEvent
from namely_python_sdk import configuration


class TestCreateEvent(unittest.TestCase):
    """CreateEvent unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
