# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.home_feed_delete_event_comment_like_response import HomeFeedDeleteEventCommentLikeResponse
from namely_python_sdk import configuration


class TestHomeFeedDeleteEventCommentLikeResponse(unittest.TestCase):
    """HomeFeedDeleteEventCommentLikeResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
