# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.home_feed_get_event_comments_response_links import HomeFeedGetEventCommentsResponseLinks
from namely_python_sdk import configuration


class TestHomeFeedGetEventCommentsResponseLinks(unittest.TestCase):
    """HomeFeedGetEventCommentsResponseLinks unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
