# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.company_resources_update_folder_name_response import CompanyResourcesUpdateFolderNameResponse
from namely_python_sdk import configuration


class TestCompanyResourcesUpdateFolderNameResponse(unittest.TestCase):
    """CompanyResourcesUpdateFolderNameResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
