# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.profile_fields_get_field_section_response_links import ProfileFieldsGetFieldSectionResponseLinks
from namely_python_sdk import configuration


class TestProfileFieldsGetFieldSectionResponseLinks(unittest.TestCase):
    """ProfileFieldsGetFieldSectionResponseLinks unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
