# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.team_links_team_categories import TeamLinksTeamCategories
from namely_python_sdk import configuration


class TestTeamLinksTeamCategories(unittest.TestCase):
    """TeamLinksTeamCategories unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
