# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.link import Link
from namely_python_sdk import configuration


class TestLink(unittest.TestCase):
    """Link unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
