# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.jobs_info_get_job_tier_response import JobsInfoGetJobTierResponse
from namely_python_sdk import configuration


class TestJobsInfoGetJobTierResponse(unittest.TestCase):
    """JobsInfoGetJobTierResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
