# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.jobs_info_create_job_tier_response_links import JobsInfoCreateJobTierResponseLinks
from namely_python_sdk import configuration


class TestJobsInfoCreateJobTierResponseLinks(unittest.TestCase):
    """JobsInfoCreateJobTierResponseLinks unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
