# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.jobs_info_update_job_title_response import JobsInfoUpdateJobTitleResponse
from namely_python_sdk import configuration


class TestJobsInfoUpdateJobTitleResponse(unittest.TestCase):
    """JobsInfoUpdateJobTitleResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
