# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.profiles_update_profile_with_new_job_title_response_linked import ProfilesUpdateProfileWithNewJobTitleResponseLinked
from namely_python_sdk import configuration


class TestProfilesUpdateProfileWithNewJobTitleResponseLinked(unittest.TestCase):
    """ProfilesUpdateProfileWithNewJobTitleResponseLinked unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
