# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.group_type import GroupType
from namely_python_sdk import configuration


class TestGroupType(unittest.TestCase):
    """GroupType unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
