# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

import unittest

import namely_python_sdk
from namely_python_sdk.model.update_folder import UpdateFolder
from namely_python_sdk import configuration


class TestUpdateFolder(unittest.TestCase):
    """UpdateFolder unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
