# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ColumnItem(BaseModel):
    # immutable name of the report column
    name: typing.Optional[str] = Field(None, alias='name')

    # data type of the report column
    type: typing.Optional[str] = Field(None, alias='type')

    # name/label of the report column
    label: typing.Optional[str] = Field(None, alias='label')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
