# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class CompensationBenefits(BaseModel):
    address1: typing.Optional[str] = Field(None, alias='address1')

    address2: typing.Optional[str] = Field(None, alias='address2')

    city: typing.Optional[str] = Field(None, alias='city')

    country_id: typing.Optional[str] = Field(None, alias='country_id')

    state_id: typing.Optional[str] = Field(None, alias='state_id')

    zip: typing.Optional[str] = Field(None, alias='zip')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
