# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class CreateEventPayload(BaseModel):
    # the content of the announcement; formatted in markdown; to @mention a profile, use format: <code>[full_name](https://developers.namely.com/)</code> where {profile_id} is the <code>id</code> of the profile you want to mention
    content: str = Field(alias='content')

    # if <code>true</code>, any @mentioned profile will be appreciated
    is_appreciation: typing.Optional[bool] = Field(None, alias='is_appreciation')

    file_id: typing.Optional[str] = Field(None, alias='file_id')

    # if <code>true</code>, will send an email to all active profiles per their company email address; will only be successful is token bearer has the corresponding permissions
    email_all: typing.Optional[bool] = Field(None, alias='email_all')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
