# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class CreateProfilePayload(BaseModel):
    first_name: str = Field(alias='first_name')

    last_name: str = Field(alias='last_name')

    # Possible values are <code>active</code>, <code>inactive</code>, or <code>pending</code>
    user_status: str = Field(alias='user_status')

    # Format is YYYY-MM-DD
    start_date: str = Field(alias='start_date')

    # Company email address
    email: str = Field(alias='email')

    # Personal email address; REQUIRED if <code>user_status</code> = <code>'pending'</code>
    personal_email: str = Field(alias='personal_email')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
