# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class CurrencyType(BaseModel):
    iso: typing.Optional[str] = Field(None, alias='iso')

    name: typing.Optional[str] = Field(None, alias='name')

    symbol: typing.Optional[str] = Field(None, alias='symbol')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
