# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class Folder(BaseModel):
    # name/label of the folder
    title: typing.Optional[str] = Field(None, alias='title')

    # unique identifier of the folder
    id: typing.Optional[str] = Field(None, alias='id')

    type: typing.Optional[str] = Field(None, alias='type')

    # number of files within the folder
    items_count: typing.Optional[int] = Field(None, alias='items_count')

    # position of the folder on the UI; 0 is the top position
    position: typing.Optional[int] = Field(None, alias='position')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
