# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.link import Link

class GetEventsResponseLinks(BaseModel):
    events.profile_: typing.Optional[Link] = Field(None, alias='events.profile')

    events.comments_: typing.Optional[Link] = Field(None, alias='events.comments')

    events.file_: typing.Optional[Link] = Field(None, alias='events.file')

    comments.profile_: typing.Optional[Link] = Field(None, alias='comments.profile')

    profile.image_: typing.Optional[Link] = Field(None, alias='profile.image')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
