# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.get_teams_response_linked import GetTeamsResponseLinked
from namely_python_sdk.pydantic.get_teams_response_links import GetTeamsResponseLinks
from namely_python_sdk.pydantic.team import Team

class GetTeamsResponse(BaseModel):
    teams: typing.Optional[typing.List[Team]] = Field(None, alias='teams')

    links: typing.Optional[GetTeamsResponseLinks] = Field(None, alias='links')

    linked: typing.Optional[GetTeamsResponseLinked] = Field(None, alias='linked')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
