# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.get_groups_response_linked import GetGroupsResponseLinked
from namely_python_sdk.pydantic.get_groups_response_links import GetGroupsResponseLinks
from namely_python_sdk.pydantic.group import Group
from namely_python_sdk.pydantic.meta_group import MetaGroup

class GetGroupsResponse(BaseModel):
    groups: typing.Optional[typing.List[Group]] = Field(None, alias='groups')

    meta: typing.Optional[MetaGroup] = Field(None, alias='meta')

    links: typing.Optional[GetGroupsResponseLinks] = Field(None, alias='links')

    linked: typing.Optional[GetGroupsResponseLinked] = Field(None, alias='linked')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
