# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.groups_teams_get_response_linked import GroupsTeamsGetResponseLinked
from namely_python_sdk.pydantic.groups_teams_get_response_links import GroupsTeamsGetResponseLinks
from namely_python_sdk.pydantic.team import Team

class GroupsTeamsGetResponse(BaseModel):
    teams: typing.Optional[typing.List[Team]] = Field(None, alias='teams')

    links: typing.Optional[GroupsTeamsGetResponseLinks] = Field(None, alias='links')

    linked: typing.Optional[GroupsTeamsGetResponseLinked] = Field(None, alias='linked')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
