# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.address import Address
from namely_python_sdk.pydantic.group_singular_links import GroupSingularLinks
from namely_python_sdk.pydantic.profile import Profile

class GroupSingular(BaseModel):
    # name/label of the group
    title: typing.Optional[str] = Field(None, alias='title')

    # unique identifier of the group
    id: typing.Optional[str] = Field(None, alias='id')

    # <code>id</code> of the group type to which the group belongs
    type: typing.Optional[str] = Field(None, alias='type')

    address: typing.Optional[Address] = Field(None, alias='address')

    links: typing.Optional[GroupSingularLinks] = Field(None, alias='links')

    linked: typing.Optional[typing.List[Profile]] = Field(None, alias='linked')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
