# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.group_type import GroupType
from namely_python_sdk.pydantic.groups_teams_get_group_type_details_response_linked import GroupsTeamsGetGroupTypeDetailsResponseLinked
from namely_python_sdk.pydantic.groups_teams_get_group_type_details_response_links import GroupsTeamsGetGroupTypeDetailsResponseLinks
from namely_python_sdk.pydantic.meta import Meta

class GroupsTeamsGetGroupTypeDetailsResponse(BaseModel):
    group_types: typing.Optional[typing.List[GroupType]] = Field(None, alias='group_types')

    meta: typing.Optional[Meta] = Field(None, alias='meta')

    links: typing.Optional[GroupsTeamsGetGroupTypeDetailsResponseLinks] = Field(None, alias='links')

    linked: typing.Optional[GroupsTeamsGetGroupTypeDetailsResponseLinked] = Field(None, alias='linked')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
