# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.comment import Comment
from namely_python_sdk.pydantic.comment_meta import CommentMeta
from namely_python_sdk.pydantic.home_feed_get_event_comments_response_linked import HomeFeedGetEventCommentsResponseLinked
from namely_python_sdk.pydantic.home_feed_get_event_comments_response_links import HomeFeedGetEventCommentsResponseLinks

class HomeFeedGetEventCommentsResponse(BaseModel):
    events: typing.Optional[typing.List[Comment]] = Field(None, alias='events')

    meta: typing.Optional[CommentMeta] = Field(None, alias='meta')

    links: typing.Optional[HomeFeedGetEventCommentsResponseLinks] = Field(None, alias='links')

    linked: typing.Optional[HomeFeedGetEventCommentsResponseLinked] = Field(None, alias='linked')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
