# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.thumb import Thumb

class Image(BaseModel):
    # unique identifier of the image
    id: typing.Optional[str] = Field(None, alias='id')

    # image's file name
    filename: typing.Optional[str] = Field(None, alias='filename')

    # image type
    mime_type: typing.Optional[str] = Field(None, alias='mime_type')

    # link of image with original resolution
    original: typing.Optional[str] = Field(None, alias='original')

    thumbs: typing.Optional[Thumb] = Field(None, alias='items')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
