# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.job_tier import JobTier
from namely_python_sdk.pydantic.jobs_info_get_job_tier_response_linked import JobsInfoGetJobTierResponseLinked
from namely_python_sdk.pydantic.jobs_info_get_job_tier_response_links import JobsInfoGetJobTierResponseLinks
from namely_python_sdk.pydantic.meta import Meta

class JobsInfoGetJobTierResponse(BaseModel):
    job_tiers: typing.Optional[typing.List[JobTier]] = Field(None, alias='job_tiers')

    meta: typing.Optional[Meta] = Field(None, alias='meta')

    links: typing.Optional[JobsInfoGetJobTierResponseLinks] = Field(None, alias='links')

    linked: typing.Optional[JobsInfoGetJobTierResponseLinked] = Field(None, alias='linked')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
