# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.jobs_info_get_all_job_titles_response_links_job_titles_job_tier import JobsInfoGetAllJobTitlesResponseLinksJobTitlesJobTier

class JobsInfoGetAllJobTitlesResponseLinks(BaseModel):
    job_titles.job_tier_: typing.Optional[JobsInfoGetAllJobTitlesResponseLinksJobTitlesJobTier] = Field(None, alias='job_titles.job_tier')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
