# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class NotificationLinks(BaseModel):
    # unique identifier of the time off request mentioned in the notification
    time_off_request_id: typing.Optional[str] = Field(None, alias='time_off_request_id')

    # id of the profile associated with the time off request mentioned in the notification
    profile_id: typing.Optional[str] = Field(None, alias='profile_id')

    # id of the profile that requested the time off mentioned in the notification; requester_id does not have to be the same as profile_id if time off was requested on someone else's behalf
    requester_id: typing.Optional[str] = Field(None, alias='requester_id')

    # only present if the request has been responded to; id of the profile that responded to the time off request mentioned in the notification
    responder_id: typing.Optional[str] = Field(None, alias='responder_id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
