# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.meta import Meta
from namely_python_sdk.pydantic.profile_fields_get_all_field_sections_response_linked import ProfileFieldsGetAllFieldSectionsResponseLinked
from namely_python_sdk.pydantic.profile_fields_get_all_field_sections_response_links import ProfileFieldsGetAllFieldSectionsResponseLinks
from namely_python_sdk.pydantic.section import Section

class ProfileFieldsGetAllFieldSectionsResponse(BaseModel):
    sections: typing.Optional[typing.List[Section]] = Field(None, alias='sections')

    meta: typing.Optional[Meta] = Field(None, alias='meta')

    links: typing.Optional[ProfileFieldsGetAllFieldSectionsResponseLinks] = Field(None, alias='links')

    linked: typing.Optional[ProfileFieldsGetAllFieldSectionsResponseLinked] = Field(None, alias='linked')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
