# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.file import File
from namely_python_sdk.pydantic.group import Group
from namely_python_sdk.pydantic.job_title import JobTitle
from namely_python_sdk.pydantic.team import Team

class ProfilesGetCurrentUserProfileResponseLinked(BaseModel):
    job_titles: typing.Optional[typing.List[JobTitle]] = Field(None, alias='job_titles')

    files: typing.Optional[typing.List[File]] = Field(None, alias='files')

    groups: typing.Optional[typing.List[Group]] = Field(None, alias='groups')

    teams: typing.Optional[typing.List[Team]] = Field(None, alias='teams')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
