# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.profile import Profile
from namely_python_sdk.pydantic.profile_links import ProfileLinks
from namely_python_sdk.pydantic.profile_meta import ProfileMeta
from namely_python_sdk.pydantic.profiles_get_current_user_profile_response_linked import ProfilesGetCurrentUserProfileResponseLinked

class ProfilesGetCurrentUserProfileResponse(BaseModel):
    profiles: typing.Optional[typing.List[Profile]] = Field(None, alias='profiles')

    meta: typing.Optional[ProfileMeta] = Field(None, alias='meta')

    links: typing.Optional[ProfileLinks] = Field(None, alias='links')

    linked: typing.Optional[ProfilesGetCurrentUserProfileResponseLinked] = Field(None, alias='linked')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
