# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.field import Field
from namely_python_sdk.pydantic.profile_fields_update_field_in_section_response_linked import ProfileFieldsUpdateFieldInSectionResponseLinked
from namely_python_sdk.pydantic.profile_fields_update_field_in_section_response_links import ProfileFieldsUpdateFieldInSectionResponseLinks
from namely_python_sdk.pydantic.profile_fields_update_field_in_section_response_meta import ProfileFieldsUpdateFieldInSectionResponseMeta

class ProfileFieldsUpdateFieldInSectionResponse(BaseModel):
    fields: typing.Optional[typing.List[Field]] = Field(None, alias='fields')

    meta: typing.Optional[ProfileFieldsUpdateFieldInSectionResponseMeta] = Field(None, alias='meta')

    links: typing.Optional[ProfileFieldsUpdateFieldInSectionResponseLinks] = Field(None, alias='links')

    linked: typing.Optional[ProfileFieldsUpdateFieldInSectionResponseLinked] = Field(None, alias='linked')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
