# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.from_namely_python_sdk_model_group_link_import_group_link import FromNamelyPythonSdkModelGroupLinkImportGroupLink
from namely_python_sdk.pydantic.from_namely_python_sdk_model_job_title_link_import_job_title_link import FromNamelyPythonSdkModelJobTitleLinkImportJobTitleLink
from namely_python_sdk.pydantic.from_namely_python_sdk_model_team_link_import_team_link import FromNamelyPythonSdkModelTeamLinkImportTeamLink
from namely_python_sdk.pydantic.group_link import GroupLink
from namely_python_sdk.pydantic.job_title_link import JobTitleLink
from namely_python_sdk.pydantic.team_link import TeamLink

class ProfileLinks(BaseModel):
    job_title: typing.Optional[JobTitleLink] = Field(None, alias='job_title')

    groups: typing.Optional[typing.List[GroupLink]] = Field(None, alias='groups')

    teams: typing.Optional[typing.List[TeamLink]] = Field(None, alias='teams')

    : typing.Optional[str] = Field(None, alias='')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
