# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.team_links import TeamLinks

class Team(BaseModel):
    # unique identifier of the team
    id: typing.Optional[str] = Field(None, alias='id')

    # name/label of the team
    name: typing.Optional[str] = Field(None, alias='name')

    # email address (@namely.com) of the team; emails all members of the team
    email: typing.Optional[str] = Field(None, alias='email')

    # epoch time of when the team was updated
    updated_at: typing.Optional[typing.Union[int, float]] = Field(None, alias='updated_at')

    # epoch time of when the team was created
    created_at: typing.Optional[typing.Union[int, float]] = Field(None, alias='created_at')

    links: typing.Optional[TeamLinks] = Field(None, alias='links')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
