# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class UpdateGroupTypePayload(BaseModel):
    # [new] name/label of the group type you're updating
    title: str = Field(alias='title')

    # if <code>true</code>, will be included on the “Teams” page in Namely and eligible for @mention (additional permissions apply)
    x_groups_as_teams: typing.Optional[bool] = Field(None, alias='x_groups_as_teams')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
