# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from namely_python_sdk.pydantic.address import Address

class UpdateGroupPayload(BaseModel):
    # [new] name/label of the group
    title: str = Field(alias='title')

    address: Address = Field(alias='address')

    # [new] group type to which the group belongs
    group_type: str = Field(alias='group_type')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
