# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from namely_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from namely_python_sdk.api_response import AsyncGeneratorResponse
from namely_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from namely_python_sdk import schemas  # noqa: F401

from namely_python_sdk.model.home_feed_remove_event_comment_response import HomeFeedRemoveEventCommentResponse as HomeFeedRemoveEventCommentResponseSchema

from namely_python_sdk.type.home_feed_remove_event_comment_response import HomeFeedRemoveEventCommentResponse

from ...api_client import Dictionary
from namely_python_sdk.pydantic.home_feed_remove_event_comment_response import HomeFeedRemoveEventCommentResponse as HomeFeedRemoveEventCommentResponsePydantic

# Path params
EventIdSchema = schemas.StrSchema
CommentIdSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'event-id': typing.Union[EventIdSchema, str, ],
        'comment-id': typing.Union[CommentIdSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_event_id = api_client.PathParameter(
    name="event-id",
    style=api_client.ParameterStyle.SIMPLE,
    schema=EventIdSchema,
    required=True,
)
request_path_comment_id = api_client.PathParameter(
    name="comment-id",
    style=api_client.ParameterStyle.SIMPLE,
    schema=CommentIdSchema,
    required=True,
)
SchemaFor200ResponseBodyApplicationJson = HomeFeedRemoveEventCommentResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: HomeFeedRemoveEventCommentResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: HomeFeedRemoveEventCommentResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _remove_event_comment_mapped_args(
        self,
        event_id: str,
        comment_id: str,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _path_params = {}
        if event_id is not None:
            _path_params["event-id"] = event_id
        if comment_id is not None:
            _path_params["comment-id"] = comment_id
        args.path = _path_params
        return args

    async def _aremove_event_comment_oapg(
        self,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Delete an Event&#x27;s Comment
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_event_id,
            request_path_comment_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'delete'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/events/{event-id}/comments/{comment-id}',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _remove_event_comment_oapg(
        self,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Delete an Event&#x27;s Comment
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_event_id,
            request_path_comment_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'delete'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/events/{event-id}/comments/{comment-id}',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class RemoveEventCommentRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aremove_event_comment(
        self,
        event_id: str,
        comment_id: str,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._remove_event_comment_mapped_args(
            event_id=event_id,
            comment_id=comment_id,
        )
        return await self._aremove_event_comment_oapg(
            path_params=args.path,
            **kwargs,
        )
    
    def remove_event_comment(
        self,
        event_id: str,
        comment_id: str,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._remove_event_comment_mapped_args(
            event_id=event_id,
            comment_id=comment_id,
        )
        return self._remove_event_comment_oapg(
            path_params=args.path,
        )

class RemoveEventComment(BaseApi):

    async def aremove_event_comment(
        self,
        event_id: str,
        comment_id: str,
        validate: bool = False,
        **kwargs,
    ) -> HomeFeedRemoveEventCommentResponsePydantic:
        raw_response = await self.raw.aremove_event_comment(
            event_id=event_id,
            comment_id=comment_id,
            **kwargs,
        )
        if validate:
            return HomeFeedRemoveEventCommentResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(HomeFeedRemoveEventCommentResponsePydantic, raw_response.body)
    
    
    def remove_event_comment(
        self,
        event_id: str,
        comment_id: str,
        validate: bool = False,
    ) -> HomeFeedRemoveEventCommentResponsePydantic:
        raw_response = self.raw.remove_event_comment(
            event_id=event_id,
            comment_id=comment_id,
        )
        if validate:
            return HomeFeedRemoveEventCommentResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(HomeFeedRemoveEventCommentResponsePydantic, raw_response.body)


class ApiFordelete(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def adelete(
        self,
        event_id: str,
        comment_id: str,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._remove_event_comment_mapped_args(
            event_id=event_id,
            comment_id=comment_id,
        )
        return await self._aremove_event_comment_oapg(
            path_params=args.path,
            **kwargs,
        )
    
    def delete(
        self,
        event_id: str,
        comment_id: str,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._remove_event_comment_mapped_args(
            event_id=event_id,
            comment_id=comment_id,
        )
        return self._remove_event_comment_oapg(
            path_params=args.path,
        )

