# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from namely_python_sdk import schemas  # noqa: F401


class Content(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    this is technically an array of arrays without any keys "sub"-arrays; each "sub"-array represents a line in the report, and is a list of values, whose position on the list within "sub"-array sequentially corresponds to the column; for example, if the second "column" is "last name", the second "value" in each "sub"-array is the value
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['ContentItem']:
            return ContentItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['ContentItem'], typing.List['ContentItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'Content':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'ContentItem':
        return super().__getitem__(i)

from namely_python_sdk.model.content_item import ContentItem
