# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from namely_python_sdk import schemas  # noqa: F401


class CountryLinks(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['CountryLinksItem']:
            return CountryLinksItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['CountryLinksItem'], typing.List['CountryLinksItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'CountryLinks':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'CountryLinksItem':
        return super().__getitem__(i)

from namely_python_sdk.model.country_links_item import CountryLinksItem
