# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from namely_python_sdk import schemas  # noqa: F401


class GroupsTeamsGetAllGroupTypesResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            
            
            class group_types(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['GroupType']:
                        return GroupType
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['GroupType'], typing.List['GroupType']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'group_types':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'GroupType':
                    return super().__getitem__(i)
        
            @staticmethod
            def meta() -> typing.Type['Meta']:
                return Meta
        
            @staticmethod
            def links() -> typing.Type['GroupsTeamsGetAllGroupTypesResponseLinks']:
                return GroupsTeamsGetAllGroupTypesResponseLinks
        
            @staticmethod
            def linked() -> typing.Type['GroupsTeamsGetAllGroupTypesResponseLinked']:
                return GroupsTeamsGetAllGroupTypesResponseLinked
            __annotations__ = {
                "group_types": group_types,
                "meta": meta,
                "links": links,
                "linked": linked,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["group_types"]) -> MetaOapg.properties.group_types: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["meta"]) -> 'Meta': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["links"]) -> 'GroupsTeamsGetAllGroupTypesResponseLinks': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["linked"]) -> 'GroupsTeamsGetAllGroupTypesResponseLinked': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["group_types", "meta", "links", "linked", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["group_types"]) -> typing.Union[MetaOapg.properties.group_types, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["meta"]) -> typing.Union['Meta', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["links"]) -> typing.Union['GroupsTeamsGetAllGroupTypesResponseLinks', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["linked"]) -> typing.Union['GroupsTeamsGetAllGroupTypesResponseLinked', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["group_types", "meta", "links", "linked", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        group_types: typing.Union[MetaOapg.properties.group_types, list, tuple, schemas.Unset] = schemas.unset,
        meta: typing.Union['Meta', schemas.Unset] = schemas.unset,
        links: typing.Union['GroupsTeamsGetAllGroupTypesResponseLinks', schemas.Unset] = schemas.unset,
        linked: typing.Union['GroupsTeamsGetAllGroupTypesResponseLinked', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'GroupsTeamsGetAllGroupTypesResponse':
        return super().__new__(
            cls,
            *args,
            group_types=group_types,
            meta=meta,
            links=links,
            linked=linked,
            _configuration=_configuration,
            **kwargs,
        )

from namely_python_sdk.model.group_type import GroupType
from namely_python_sdk.model.groups_teams_get_all_group_types_response_linked import GroupsTeamsGetAllGroupTypesResponseLinked
from namely_python_sdk.model.groups_teams_get_all_group_types_response_links import GroupsTeamsGetAllGroupTypesResponseLinks
from namely_python_sdk.model.meta import Meta
