# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from namely_python_sdk import schemas  # noqa: F401


class ProfilesUpdateProfileWithNewJobTitleResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            
            
            class profiles(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Profile']:
                        return Profile
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Profile'], typing.List['Profile']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'profiles':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Profile':
                    return super().__getitem__(i)
        
            @staticmethod
            def meta() -> typing.Type['ProfilesUpdateProfileWithNewJobTitleResponseMeta']:
                return ProfilesUpdateProfileWithNewJobTitleResponseMeta
        
            @staticmethod
            def links() -> typing.Type['ProfilesUpdateProfileWithNewJobTitleResponseLinks']:
                return ProfilesUpdateProfileWithNewJobTitleResponseLinks
        
            @staticmethod
            def linked() -> typing.Type['ProfilesUpdateProfileWithNewJobTitleResponseLinked']:
                return ProfilesUpdateProfileWithNewJobTitleResponseLinked
            __annotations__ = {
                "profiles": profiles,
                "meta": meta,
                "links": links,
                "linked": linked,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["profiles"]) -> MetaOapg.properties.profiles: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["meta"]) -> 'ProfilesUpdateProfileWithNewJobTitleResponseMeta': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["links"]) -> 'ProfilesUpdateProfileWithNewJobTitleResponseLinks': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["linked"]) -> 'ProfilesUpdateProfileWithNewJobTitleResponseLinked': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["profiles", "meta", "links", "linked", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["profiles"]) -> typing.Union[MetaOapg.properties.profiles, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["meta"]) -> typing.Union['ProfilesUpdateProfileWithNewJobTitleResponseMeta', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["links"]) -> typing.Union['ProfilesUpdateProfileWithNewJobTitleResponseLinks', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["linked"]) -> typing.Union['ProfilesUpdateProfileWithNewJobTitleResponseLinked', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["profiles", "meta", "links", "linked", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        profiles: typing.Union[MetaOapg.properties.profiles, list, tuple, schemas.Unset] = schemas.unset,
        meta: typing.Union['ProfilesUpdateProfileWithNewJobTitleResponseMeta', schemas.Unset] = schemas.unset,
        links: typing.Union['ProfilesUpdateProfileWithNewJobTitleResponseLinks', schemas.Unset] = schemas.unset,
        linked: typing.Union['ProfilesUpdateProfileWithNewJobTitleResponseLinked', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ProfilesUpdateProfileWithNewJobTitleResponse':
        return super().__new__(
            cls,
            *args,
            profiles=profiles,
            meta=meta,
            links=links,
            linked=linked,
            _configuration=_configuration,
            **kwargs,
        )

from namely_python_sdk.model.profile import Profile
from namely_python_sdk.model.profiles_update_profile_with_new_job_title_response_linked import ProfilesUpdateProfileWithNewJobTitleResponseLinked
from namely_python_sdk.model.profiles_update_profile_with_new_job_title_response_links import ProfilesUpdateProfileWithNewJobTitleResponseLinks
from namely_python_sdk.model.profiles_update_profile_with_new_job_title_response_meta import ProfilesUpdateProfileWithNewJobTitleResponseMeta
