# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from namely_python_sdk import schemas  # noqa: F401


class ProfileLinks(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def job_title() -> typing.Type['JobTitleLink']:
                return JobTitleLink
            
            
            class groups(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['GroupLink']:
                        return GroupLink
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['GroupLink'], typing.List['GroupLink']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'groups':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'GroupLink':
                    return super().__getitem__(i)
            
            
            class teams(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['TeamLink']:
                        return TeamLink
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['TeamLink'], typing.List['TeamLink']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'teams':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'TeamLink':
                    return super().__getitem__(i)
             = schemas.StrSchema
            __annotations__ = {
                "job_title": job_title,
                "groups": groups,
                "teams": teams,
                "": ,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["job_title"]) -> 'JobTitleLink': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["groups"]) -> MetaOapg.properties.groups: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["teams"]) -> MetaOapg.properties.teams: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal[""]) -> MetaOapg.properties.: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["job_title", "groups", "teams", "", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["job_title"]) -> typing.Union['JobTitleLink', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["groups"]) -> typing.Union[MetaOapg.properties.groups, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["teams"]) -> typing.Union[MetaOapg.properties.teams, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal[""]) -> typing.Union[MetaOapg.properties., schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["job_title", "groups", "teams", "", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        job_title: typing.Union['JobTitleLink', schemas.Unset] = schemas.unset,
        groups: typing.Union[MetaOapg.properties.groups, list, tuple, schemas.Unset] = schemas.unset,
        teams: typing.Union[MetaOapg.properties.teams, list, tuple, schemas.Unset] = schemas.unset,
        : typing.Union[MetaOapg.properties., str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ProfileLinks':
        return super().__new__(
            cls,
            *args,
            job_title=job_title,
            groups=groups,
            teams=teams,
            =,
            _configuration=_configuration,
            **kwargs,
        )

from namely_python_sdk.model.from_namely_python_sdk_model_group_link_import_group_link import FromNamelyPythonSdkModelGroupLinkImportGroupLink
from namely_python_sdk.model.from_namely_python_sdk_model_job_title_link_import_job_title_link import FromNamelyPythonSdkModelJobTitleLinkImportJobTitleLink
from namely_python_sdk.model.from_namely_python_sdk_model_team_link_import_team_link import FromNamelyPythonSdkModelTeamLinkImportTeamLink
