# coding: utf-8

"""
    Namely API

    Move your app forward with the Namely API Move your app forward with the Namely API

    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from namely_python_sdk import schemas  # noqa: F401


class UpdateFolder(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "folders",
        }
        
        class properties:
            
            
            class folders(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['UpdateFolderPayload']:
                        return UpdateFolderPayload
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['UpdateFolderPayload'], typing.List['UpdateFolderPayload']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'folders':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'UpdateFolderPayload':
                    return super().__getitem__(i)
            __annotations__ = {
                "folders": folders,
            }
    
    folders: MetaOapg.properties.folders
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["folders"]) -> MetaOapg.properties.folders: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["folders", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["folders"]) -> MetaOapg.properties.folders: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["folders", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        folders: typing.Union[MetaOapg.properties.folders, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UpdateFolder':
        return super().__new__(
            cls,
            *args,
            folders=folders,
            _configuration=_configuration,
            **kwargs,
        )

from namely_python_sdk.model.update_folder_payload import UpdateFolderPayload
